apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unizo-repo-subscriber.fullname" . }}-config
  labels:
    {{- include "unizo-repo-subscriber.labels" . | nindent 4 }}
data:
  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}