apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unizo-repo-subscriber.fullname" . }}-secrets
  labels:
    {{- include "unizo-repo-subscriber.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secrets }}
  {{ .key }}: {{ .value | b64enc | quote }}
  {{- end }}